/**
 * 成就系统初始化数据
 * 可以通过管理员接口批量创建这些成就
 */

export const INITIAL_ACHIEVEMENTS = [
  // 文章相关成就
  {
    code: 'FIRST_ARTICLE',
    name: '初出茅庐',
    description: '发布第一篇文章',
    icon: '',
    type: 'ARTICLE',
    rarity: 'COMMON',
    condition: { type: 'count', target: 1, event: 'article.created' },
    rewardPoints: 10,
    rewardExp: 50,
    hidden: false,
    sort: 1,
  },
  {
    code: 'ARTICLE_10',
    name: '笔耕不辍',
    description: '发布10篇文章',
    icon: '',
    type: 'ARTICLE',
    rarity: 'COMMON',
    condition: { type: 'count', target: 10, event: 'article.created' },
    rewardPoints: 50,
    rewardExp: 200,
    hidden: false,
    sort: 2,
  },
  {
    code: 'ARTICLE_50',
    name: '著作等身',
    description: '发布50篇文章',
    icon: '',
    type: 'ARTICLE',
    rarity: 'RARE',
    condition: { type: 'count', target: 50, event: 'article.created' },
    rewardPoints: 200,
    rewardExp: 1000,
    hidden: false,
    sort: 3,
  },
  {
    code: 'ARTICLE_100',
    name: '文坛巨匠',
    description: '发布100篇文章',
    icon: '',
    type: 'ARTICLE',
    rarity: 'EPIC',
    condition: { type: 'count', target: 100, event: 'article.created' },
    rewardPoints: 500,
    rewardExp: 3000,
    hidden: false,
    sort: 4,
  },

  // 点赞相关成就
  {
    code: 'FIRST_LIKE',
    name: '初获认可',
    description: '文章获得第一个点赞',
    icon: '',
    type: 'ARTICLE',
    rarity: 'COMMON',
    condition: { type: 'count', target: 1, event: 'article.receivedLike' },
    rewardPoints: 5,
    rewardExp: 20,
    hidden: false,
    sort: 10,
  },
  {
    code: 'LIKE_100',
    name: '人气作者',
    description: '文章累计获得100个点赞',
    icon: '',
    type: 'ARTICLE',
    rarity: 'RARE',
    condition: { type: 'count', target: 100, event: 'article.receivedLike' },
    rewardPoints: 100,
    rewardExp: 500,
    hidden: false,
    sort: 11,
  },
  {
    code: 'LIKE_1000',
    name: '万众瞩目',
    description: '文章累计获得1000个点赞',
    icon: '',
    type: 'ARTICLE',
    rarity: 'EPIC',
    condition: { type: 'count', target: 1000, event: 'article.receivedLike' },
    rewardPoints: 500,
    rewardExp: 2000,
    hidden: false,
    sort: 12,
  },

  // 评论相关成就
  {
    code: 'FIRST_COMMENT',
    name: '初次发声',
    description: '发表第一条评论',
    icon: '',
    type: 'COMMENT',
    rarity: 'COMMON',
    condition: { type: 'count', target: 1, event: 'comment.created' },
    rewardPoints: 5,
    rewardExp: 20,
    hidden: false,
    sort: 20,
  },
  {
    code: 'COMMENT_100',
    name: '热心网友',
    description: '发表100条评论',
    icon: '',
    type: 'COMMENT',
    rarity: 'RARE',
    condition: { type: 'count', target: 100, event: 'comment.created' },
    rewardPoints: 100,
    rewardExp: 500,
    hidden: false,
    sort: 21,
  },

  // 社交相关成就
  {
    code: 'FIRST_FOLLOW',
    name: '结识好友',
    description: '关注第一个用户',
    icon: '',
    type: 'SOCIAL',
    rarity: 'COMMON',
    condition: { type: 'count', target: 1, event: 'user.followed' },
    rewardPoints: 5,
    rewardExp: 20,
    hidden: false,
    sort: 30,
  },
  {
    code: 'FOLLOW_10',
    name: '社交达人',
    description: '关注10个用户',
    icon: '',
    type: 'SOCIAL',
    rarity: 'COMMON',
    condition: { type: 'count', target: 10, event: 'user.followed' },
    rewardPoints: 30,
    rewardExp: 100,
    hidden: false,
    sort: 31,
  },
  {
    code: 'FIRST_FOLLOWER',
    name: '初获关注',
    description: '获得第一个粉丝',
    icon: '',
    type: 'SOCIAL',
    rarity: 'COMMON',
    condition: { type: 'count', target: 1, event: 'user.receivedFollow' },
    rewardPoints: 10,
    rewardExp: 50,
    hidden: false,
    sort: 32,
  },
  {
    code: 'FOLLOWER_100',
    name: '小有名气',
    description: '获得100个粉丝',
    icon: '',
    type: 'SOCIAL',
    rarity: 'RARE',
    condition: { type: 'count', target: 100, event: 'user.receivedFollow' },
    rewardPoints: 200,
    rewardExp: 1000,
    hidden: false,
    sort: 33,
  },
  {
    code: 'FOLLOWER_1000',
    name: '名声在外',
    description: '获得1000个粉丝',
    icon: '',
    type: 'SOCIAL',
    rarity: 'EPIC',
    condition: { type: 'count', target: 1000, event: 'user.receivedFollow' },
    rewardPoints: 1000,
    rewardExp: 5000,
    hidden: false,
    sort: 34,
  },

  // 等级相关成就
  {
    code: 'LEVEL_10',
    name: '初窥门径',
    description: '达到10级',
    icon: '',
    type: 'LEVEL',
    rarity: 'COMMON',
    condition: { type: 'threshold', target: 10, event: 'user.levelUp' },
    rewardPoints: 50,
    rewardExp: 0,
    hidden: false,
    sort: 40,
  },
  {
    code: 'LEVEL_30',
    name: '登堂入室',
    description: '达到30级',
    icon: '',
    type: 'LEVEL',
    rarity: 'RARE',
    condition: { type: 'threshold', target: 30, event: 'user.levelUp' },
    rewardPoints: 200,
    rewardExp: 0,
    hidden: false,
    sort: 41,
  },
  {
    code: 'LEVEL_50',
    name: '炉火纯青',
    description: '达到50级',
    icon: '',
    type: 'LEVEL',
    rarity: 'EPIC',
    condition: { type: 'threshold', target: 50, event: 'user.levelUp' },
    rewardPoints: 500,
    rewardExp: 0,
    hidden: false,
    sort: 42,
  },

  // 特殊成就
  {
    code: 'LOGIN_7_DAYS',
    name: '坚持不懈',
    description: '连续登录7天',
    icon: '',
    type: 'SPECIAL',
    rarity: 'COMMON',
    condition: { type: 'consecutive', target: 7, event: 'user.dailyLogin' },
    rewardPoints: 50,
    rewardExp: 200,
    hidden: false,
    sort: 50,
  },
  {
    code: 'LOGIN_30_DAYS',
    name: '持之以恒',
    description: '连续登录30天',
    icon: '',
    type: 'SPECIAL',
    rarity: 'RARE',
    condition: { type: 'consecutive', target: 30, event: 'user.dailyLogin' },
    rewardPoints: 300,
    rewardExp: 1000,
    hidden: false,
    sort: 51,
  },
  {
    code: 'BECOME_MEMBER',
    name: '尊贵会员',
    description: '成为会员',
    icon: '',
    type: 'SPECIAL',
    rarity: 'RARE',
    condition: { type: 'once', target: 1, event: 'membership.purchased' },
    rewardPoints: 100,
    rewardExp: 500,
    hidden: false,
    sort: 52,
  },
  {
    code: 'PROFILE_COMPLETED',
    name: '完美档案',
    description: '完善个人资料',
    icon: '',
    type: 'SPECIAL',
    rarity: 'COMMON',
    condition: { type: 'once', target: 1, event: 'user.profileCompleted' },
    rewardPoints: 20,
    rewardExp: 100,
    hidden: false,
    sort: 53,
  },
];
