/**
 * 积分活动种子数据（合并规则和任务）
 * 可以在应用启动时初始化这些活动
 */
export const POINTS_ACTIVITIES_SEED = [
  // 即时积分奖励（原 PointsRule）
  {
    code: 'DAILY_LOGIN',
    name: '每日登录',
    description: '每天首次登录获得积分',
    type: 'INSTANT',
    rewardPoints: 10,
    targetCount: 1,
    dailyLimit: 1,
    totalLimit: 0,
    validDays: 365,
    icon: '🎯',
    link: null,
    isActive: true,
    sort: 1,
  },
  {
    code: 'PUBLISH_ARTICLE',
    name: '发布文章',
    description: '发布一篇文章获得积分',
    type: 'INSTANT',
    rewardPoints: 50,
    targetCount: 1,
    dailyLimit: 5,
    totalLimit: 0,
    validDays: 0,
    icon: '📝',
    link: null,
    isActive: true,
    sort: 2,
  },
  {
    code: 'COMMENT_ARTICLE',
    name: '评论文章',
    description: '评论文章获得积分',
    type: 'INSTANT',
    rewardPoints: 5,
    targetCount: 1,
    dailyLimit: 10,
    totalLimit: 0,
    validDays: 0,
    icon: '💬',
    link: null,
    isActive: true,
    sort: 3,
  },
  {
    code: 'LIKE_ARTICLE',
    name: '点赞文章',
    description: '点赞文章获得积分',
    type: 'INSTANT',
    rewardPoints: 2,
    targetCount: 1,
    dailyLimit: 20,
    totalLimit: 0,
    validDays: 0,
    icon: '👍',
    link: null,
    isActive: true,
    sort: 4,
  },
  {
    code: 'SHARE_ARTICLE',
    name: '分享文章',
    description: '分享文章获得积分',
    type: 'INSTANT',
    rewardPoints: 10,
    targetCount: 1,
    dailyLimit: 5,
    totalLimit: 0,
    validDays: 0,
    icon: '📤',
    link: null,
    isActive: true,
    sort: 5,
  },
  {
    code: 'INVITE_USER',
    name: '邀请用户',
    description: '成功邀请一位用户注册',
    type: 'INSTANT',
    rewardPoints: 100,
    targetCount: 1,
    dailyLimit: 0,
    totalLimit: 0,
    validDays: 0,
    icon: '👥',
    link: '/invite',
    isActive: true,
    sort: 6,
  },
  {
    code: 'COMPLETE_PROFILE',
    name: '完善资料',
    description: '完善个人资料获得积分',
    type: 'ONCE',
    rewardPoints: 50,
    targetCount: 1,
    dailyLimit: 0,
    totalLimit: 1,
    validDays: 0,
    icon: '👤',
    link: '/profile',
    isActive: true,
    sort: 7,
  },
  
  // 周期性任务（原 PointsTask）
  {
    code: 'DAILY_SIGN_IN_TASK',
    name: '每日签到任务',
    description: '每天登录一次即可完成',
    type: 'DAILY',
    rewardPoints: 20,
    targetCount: 1,
    dailyLimit: 1,
    totalLimit: 0,
    validDays: 0,
    icon: '📅',
    link: null,
    isActive: true,
    sort: 10,
  },
  {
    code: 'PUBLISH_3_ARTICLES_WEEKLY',
    name: '每周发布3篇文章',
    description: '本周发布3篇文章获得额外奖励',
    type: 'WEEKLY',
    rewardPoints: 200,
    targetCount: 3,
    dailyLimit: 0,
    totalLimit: 0,
    validDays: 0,
    icon: '✍️',
    link: '/article/create',
    isActive: true,
    sort: 11,
  },
  {
    code: 'COMMENT_10_TIMES_WEEKLY',
    name: '每周评论10次',
    description: '本周评论10次获得额外奖励',
    type: 'WEEKLY',
    rewardPoints: 100,
    targetCount: 10,
    dailyLimit: 0,
    totalLimit: 0,
    validDays: 0,
    icon: '💬',
    link: null,
    isActive: true,
    sort: 12,
  },
  {
    code: 'INVITE_5_USERS_ACHIEVEMENT',
    name: '邀请达人',
    description: '累计邀请5位好友注册',
    type: 'ONCE',
    rewardPoints: 500,
    targetCount: 5,
    dailyLimit: 0,
    totalLimit: 1,
    validDays: 0,
    icon: '🏆',
    link: '/invite',
    isActive: true,
    sort: 13,
  },
];
