/**
 * 积分规则种子数据
 * 可以在应用启动时初始化这些规则
 */
export const POINTS_RULES_SEED = [
  {
    code: 'DAILY_LOGIN',
    name: '每日登录',
    description: '每天首次登录获得积分',
    points: 10,
    dailyLimit: 1,
    totalLimit: 0,
    validDays: 365,
    isActive: true,
    sort: 1,
  },
  {
    code: 'PUBLISH_ARTICLE',
    name: '发布文章',
    description: '发布一篇文章获得积分',
    points: 50,
    dailyLimit: 5,
    totalLimit: 0,
    validDays: 0,
    isActive: true,
    sort: 2,
  },
  {
    code: 'COMMENT_ARTICLE',
    name: '评论文章',
    description: '评论文章获得积分',
    points: 5,
    dailyLimit: 10,
    totalLimit: 0,
    validDays: 0,
    isActive: true,
    sort: 3,
  },
  {
    code: 'LIKE_ARTICLE',
    name: '点赞文章',
    description: '点赞文章获得积分',
    points: 2,
    dailyLimit: 20,
    totalLimit: 0,
    validDays: 0,
    isActive: true,
    sort: 4,
  },
  {
    code: 'SHARE_ARTICLE',
    name: '分享文章',
    description: '分享文章获得积分',
    points: 10,
    dailyLimit: 5,
    totalLimit: 0,
    validDays: 0,
    isActive: true,
    sort: 5,
  },
  {
    code: 'INVITE_USER',
    name: '邀请用户',
    description: '成功邀请一位用户注册',
    points: 100,
    dailyLimit: 0,
    totalLimit: 0,
    validDays: 0,
    isActive: true,
    sort: 6,
  },
  {
    code: 'COMPLETE_PROFILE',
    name: '完善资料',
    description: '完善个人资料获得积分',
    points: 50,
    dailyLimit: 0,
    totalLimit: 1,
    validDays: 0,
    isActive: true,
    sort: 7,
  },
];

/**
 * 积分任务种子数据
 */
export const POINTS_TASKS_SEED = [
  {
    code: 'DAILY_LOGIN_TASK',
    name: '每日签到',
    description: '每天登录一次即可完成',
    type: 'DAILY',
    rewardPoints: 10,
    targetCount: 1,
    icon: '📅',
    link: null,
    isActive: true,
    sort: 1,
  },
  {
    code: 'PUBLISH_3_ARTICLES',
    name: '发布3篇文章',
    description: '本周发布3篇文章',
    type: 'WEEKLY',
    rewardPoints: 200,
    targetCount: 3,
    icon: '✍️',
    link: '/article/create',
    isActive: true,
    sort: 2,
  },
  {
    code: 'COMMENT_10_TIMES',
    name: '评论10次',
    description: '本周评论10次',
    type: 'WEEKLY',
    rewardPoints: 100,
    targetCount: 10,
    icon: '💬',
    link: null,
    isActive: true,
    sort: 3,
  },
  {
    code: 'INVITE_5_USERS',
    name: '邀请5位好友',
    description: '邀请5位好友注册',
    type: 'ONCE',
    rewardPoints: 500,
    targetCount: 5,
    icon: '👥',
    link: '/invite',
    isActive: true,
    sort: 4,
  },
];
